In [ ]:
!pip install -r requirements.txt

In [97]:
import numpy as np

In [98]:
theta1 = np.array([[0.5, 0.2], [0.6, -0.1], [-0.4,-0.3]])
theta1.shape

(3, 2)

In [99]:
theta2 = np.array([[0.7, -0.1, 0.2]])
theta2.shape

(1, 3)

In [100]:
x = np.array([[0.5, 0.1], [0.2, 0.6]])

y = np.array([[0.6], [0.8]])

Pré ativação da 1° camada: $z^{1} = x\cdot\theta^{1^\top}$

In [101]:
z1 = np.matmul(x, theta1.T)
z1

array([[ 0.27,  0.29, -0.23],
       [ 0.22,  0.06, -0.26]])

Função de ativação da 1° camada: $a^{1} = \sigma(z^{1})$

In [102]:
def sigmoid(z):
    return 1/1 + np.exp(-z)

a1 = sigmoid(z1)
a1

array([[1.76337949, 1.74826357, 2.25860001],
       [1.8025188 , 1.94176453, 2.29693009]])

In [103]:
z2 = np.matmul(a1, theta2.T)
z2

array([[1.51125929],
       [1.52697272]])

In [104]:
a2 = sigmoid(z2)
a2

array([[1.22063196],
       [1.21719217]])

Loss Function

In [105]:
r = y - a2
loss = np.matmul(r.T, r) / 2
#loss = np.sum((y - a2)**2) / 2
loss

array([[0.27961667]])

Backward Pass 

$\frac{\partial J}{\partial a^{(2)} -y}$

In [106]:
dJda2 = a2 - y
dJdz2 = a2 * (1 - a2)

delta2 = dJda2 * dJdz2
delta2

array([[-0.16714266],
       [-0.11029085]])

  $\frac{\partial a1{(2)}} {\partial z^{(2)} = a^{(2)}}\cdot(1 - a^{(2)}) $

In [107]:
da1dz1 = a1 * (1 - a1)
delta1 = np.matmul(delta2, theta2) * da1dz1
delta1

array([[ 0.15749676, -0.02186497,  0.09502642],
       [ 0.11167926, -0.02016872,  0.06571036]])

In [108]:
dJdtheta1 = np.matmul(delta1.T, x)
dJdtheta2 = np.matmul(delta2.T, a1)

dJdtheta1, dJdtheta2

(array([[ 0.10108423,  0.08275723],
        [-0.01496623, -0.01428773],
        [ 0.06065528,  0.04892885]]),
 array([[-0.49353726, -0.50636828, -0.63083878]]))

Optimize: $\theta_{t+1} = \theta_{t} - \eta *\nabla J$

In [111]:
new_theta1 = theta1 - 0.1 * dJdtheta1
new_theta2 = theta2 - 0.1 * dJdtheta2

theta1, new_theta1, theta2, new_theta2


(array([[ 0.5,  0.2],
        [ 0.6, -0.1],
        [-0.4, -0.3]]),
 array([[ 0.48989158,  0.19172428],
        [ 0.60149662, -0.09857123],
        [-0.40606553, -0.30489289]]),
 array([[ 0.7, -0.1,  0.2]]),
 array([[ 0.74935373, -0.04936317,  0.26308388]]))